### ISSUE TITLE
部分装备的获取难度和掉落

### ISSUE THREAD

**Issue by shengqin** [lamueno/classicDruid#11]
`火喉披风`的掉落是BWL费尔默，难度认为是三星。`强者斗篷`获取难度认为也是三星。另外`褴褛皮帽`和`瘟疫犬护腿`是两件掉率十分低的装备，是否可以考虑将难度变为2星。

**Comment by lamueno** [comment]
两件披风的难度调整了。褴褛和瘟疫犬因为是装备，可以直接从AH获取，统一不设置获取难度
