### ISSUE TITLE
槌击是否二次圆桌？元素磨刀石究竟有没有用？

### ISSUE THREAD

**Issue by lamueno** [lamueno/classicDruid#13]
[怀旧服熊T仇恨向配装的属性选择](https://nga.178.com/read.php?tid=21250240) 一文提出了槌击的暴击应采用二次圆桌判定，实际暴击率远低于面板暴击。这是一个非常值得关注的切入点，可惜数据量偏少。

因此，我计划去厄运木桩做一趟测试，顺便测试槌击是否受元素磨刀石影响。

之前noobs Nc的[帖子](https://nga.178.com/read.php?tid=19446432)提出元素磨刀石仅对白字有效，但因提供的数据在统计上不显著，后有统计大佬另外做了测试，给出了不一样的结论，并且具有统计意义：[狂暴战元素磨刀石测试~结论可能大跌眼镜。](https://nga.178.com/read.php?tid=20501914)。

**Comment by hapshon** [comment]
最新研究成果表明，技能受到到元素磨刀石加成，属于特殊附着武器效果，占用一buff位。https://bbs.nga.cn/read.php?tid=20176615&fav=6d6496b1(元素磨刀石是否对技能暴击率有影响 5000次斩杀测试)

**Comment by bluedancel** [comment]
怀旧服最近有修改，元素磨刀石的作用机制变化了，最新的好像是作用于主副手和技能，但是变熊不享受。

**Comment by lamueno** [comment]
槌击为二次圆桌。
元素磨刀石已经无效。
