### ISSUE TITLE
[赞达拉英雄徽记] 这个怎么样

### ISSUE THREAD

**Issue by k99k5** [lamueno/classicDruid#14]
哈卡之心换的那个

**Comment by k99k5** [comment]
有评分吗= = 。

**Comment by lamueno** [comment]
你猜为啥没评分 ^^

价值一般。这是个为战士设计的饰品，当然战士估计也看不上。

1. uptime
开启时间20s，2分钟冷却。那么期望覆盖率就是16%。考虑最好的情况，2分20秒的战斗，正好开启2次，覆盖率也才28%。

2. 特效
这个特效意味着你希望在开启期间尽量不要被击中。满打满算，假设开启期间次次都躲闪，那期望就是2000护甲，30防御=1.2未命中+1.2躲闪=2.4躲闪

3. 特效*覆盖率
都往最高的算，相当于560护甲，0.67躲闪。而实际上可能只是上述数值的1/3左右。

对比暴君常驻的910护甲，1躲闪。

**Comment by lamueno** [comment]
已经更新到评分里了
