### ISSUE TITLE
为什么R8的裤子和我查到的差这么多？

### ISSUE THREAD

**Issue by GuoJock** [lamueno/classicDruid#16]
为什么R8的裤子和我查到的差这么多？我查到的还有1闪避12攻强，加起来应该比祖格的好吧？
![image](https://user-images.githubusercontent.com/24932067/81152082-312adf80-8fb4-11ea-8bf5-2657883f9afc.png)

![image](https://user-images.githubusercontent.com/24932067/81152148-4142bf00-8fb4-11ea-843c-c86771b7b997.png)

**Comment by GuoJock** [comment]
上传的截图貌似看不到 不知道什么原因，总之希望楼主核对一下

**Comment by lamueno** [comment]
你好，这个是旧版的套装。目前游戏实装的是新版。

【旧版】少校的圣装：
https://cn.classic.wowhead.com/item-set=381/

【新版】少校的庇护：
https://cn.classic.wowhead.com/item-set=551/
