### ISSUE TITLE
您好 请教下您的加成耐力计算方式

### ISSUE THREAD

**Issue by hapshon** [lamueno/classicDruid#18]
1耐力 = 10 * 野性之心1.2 * 耐久1.05 * 摩尔达的勇气1.15 * 赞达拉之魂1.15 = 16.6635生命
每次buff都在前一次的buff基础上提升、通俗点说类似利滚利的计算方式
我只是猜测这样计算是否有问题，是否都从基础属性上计算更合理？
1耐力=10（1+0.2+0.05+0.15+0.15）=15.5生命。
诚心请教，期待您的回答。

**Comment by lamueno** [comment]
属性类buff都采用乘法计算，这点已经反复在游戏中测试验证。您也可以亲自测试一下
