### ISSUE TITLE
护甲得分低了，攻强得分高了

### ISSUE THREAD

**Issue by leippking** [lamueno/classicDruid#2]
一、护甲得分低：
60年代，75%并不是物免上限。
证明：
1.黑暗深渊的那个乌龟boss猎人收了之后，出bug后，护甲过亿，物免99.9X%的截图。
2.N服，熊T帕奇维克，护甲23XXX护甲减免8X%的截图。
3.怀旧服，吃满石盾等buff，牧师+圣疗，20XXX护甲减免79%的截图。

另外，护甲受牧师天赋（常规），萨满天赋（常规）/骑士天赋（非常规）的护甲加成。
可以按联盟+25%，部落+50%计算。

二、力量/攻强得分高：
力量属性/攻强属性得分过高。举两个例子：
1.骨环头盔得分》迅影头得分。这两件装备专职熊T基本都刷出来过，实际体验骨环远强于迅影头。
2.苍白鞋子得分=灰烬鞋子得分。明显灰烬应该得分高于苍白鞋子。
3.单手的奇拉战锤》》》双手典狱官。 实际上N服的前辈们，2件都带身上，但是使用场合一半一半吧。说明实际体验两者是一致的，相互补充没有明显差距。

其他的属性评分上，观点一致。
感谢！

**Comment by JarvanDing** [comment]
护甲只能抵抗物理攻击，对于属性攻击好像没啥用，所以才降分得吧？

**Comment by lamueno** [comment]
### 护甲问题
- 目前的模型既没有考虑上限也没有考虑buff，因为达到上限之后就不是线性的，纳入模型难以保持一致性。
- 护甲上限目前基本各个资料网站的观点是一致的。游戏截图如果是实际伤害减免的对比，我觉得可以采信。如果只是角色面板，那么看那个显示其实不代表实际情况的。就比如火抗我也可以堆到400+，但实际上跟300+没有差别。
- 可能后续会单独出一版算上各类buff的情况看看

### 力量/攻强问题
- 这部分我综合您说的1,2,3，理解为仇恨属性得分都高
- 其实也可以认为是仇恨/生存权重的问题。目前是直接相加，即1:1。这个也是我自己存疑的一点
- 后续会尝试调整权重。

**Comment by lamueno** [comment]
https://shimo.im/sheets/rHCxGcKhWtcKJRGY/Lqpez/

粗暴地将仇恨分*50% 这样的结果看起来如何？
