### ISSUE TITLE
关于F1 F2 F3快捷键

### ISSUE THREAD

**Issue by ldkvfeng** [lamueno/classicDruid#22]
感谢大大的无私分享，您的熊宏键位是我的启蒙，最近导入大大的键位，其中F1 F2 F3无效，想修改对应键位，但不知道里面的含义例如：
/select 超强法力药水,特效法力药水,强效法力药水,法力药水,次级法力药水,初级法力药水
/click [btn:2]S027M;S027A
其中/click [btn:2]S027M;S027A什么意思，尤其是S027M;S027A不太懂含义，请赐教

**Comment by lamueno** [comment]
你好，需要安装一个名叫「select」的插件。
`/click [btn:2]S027M;S027A` 是插件自动生成的

**Comment by ldkvfeng** [comment]
谢谢老大指点，我试试！

**Comment by ldkvfeng** [comment]
谢谢您的回复，已经使用上了再次感谢

lamueno <notifications@github.com> 于2020年8月28日周五 上午11:06写道：
