### ISSUE TITLE
护甲免伤可能没有上限

### ISSUE THREAD

**Issue by Onedayinabar** [lamueno/classicDruid#4]
理由
1.在某玩家提供的后期版本熊形态属性图中，面板显示78.3%免伤
2.有玩家称魔兽世界是到70版本时因为熊护甲过高才加入限制，言外之意是60版本没有护甲上限
目前没有具体测试结果

**Comment by lamueno** [comment]
应该是显示问题。

这里有[测试](https://nga.178.com/read.php?tid=19256184)
