### ISSUE TITLE
关于抢怪宏的建议

### ISSUE THREAD

**Issue by honggu025** [lamueno/classicDruid#6]
1，我查了怀旧服的api，EditMacro只有4个参数，所以最后的“1，1”没有意义，去掉完全没有影响，可以节省空间。
2，/cleartarget [dead]没有必要，因为/tar命令如果有存活的匹配就会忽略死亡的匹配，只有在附近没有活着的匹配时，才会选择死亡的目标，如果选择了死亡的目标，就意味着附近没有存活的匹配了，可以去掉节省空间。
3，/stopmacro [noexists]也没有必要，因为SetRaidTarget("target",4)是为当前目标设置标记，从逻辑上来讲，前面的/cleartarget /tar xxx命令会出现三种情况：1）正常选择目标（附近有存活的匹配）。2）选择了死亡的目标（附近没有存活的匹配但是有死亡的匹配）。3）没有选择目标（活的死的都没有）。这三种情况下执行SetRaidTarget命令都不会产生错误，所以没必要停止宏的运行。
4，format命令也没有必要，反而不如用..连接字符串省空间。
综上，我把宏改成了255字符以内，不需要超长宏插件了
`/run local m,s;m=UnitName("target");s=m and " "..m or "getenemy";EditMacro("锁",nil,nil,"/click [mod]ElvUI_Bar4Button6\n/stopmacro [mod]\n/cleartarget\n/tar"..s.."\n/run  if GetRaidTargetIndex(\"target\")~=6 then SetRaidTarget(\"target\",6)end")
`

**Comment by lamueno** [comment]
好评！感谢提点

如果在把 and UnitHealth("target")<100 作为判断条件加进去，还有办法挤进255字符么
