### ISSUE TITLE
小白请教猫形态下非隐身，目标为敌对，Q没有撕碎

### ISSUE THREAD

**Issue by edwards19900128** [lamueno/classicDruid#8]
Q一直提示隐身

**Comment by lamueno** [comment]
就是这样设计的：非战斗状态会隐身然后打毁灭；战斗状态会打撕碎。

**Comment by edwards19900128** [comment]
> 就是这样设计的：非战斗状态会隐身然后打毁灭；战斗状态会打撕碎。
哦哦 可能是我在野外的时候直接想就猫上去打撕碎了。。。楼主键位和宏都很精细 对新手帮助非常大。。话说还有对战士有研究吗

**Comment by lamueno** [comment]
谢谢。帮朋友写过一套防战的键位，但是自己玩得时间少还不完善

**Comment by edwards19900128** [comment]
> 谢谢。帮朋友写过一套防战的键位，但是自己玩得时间少还不完善

可以的话想学习下防战键位。。。
