### ISSUE TITLE
手腕-巡林者护腕的获取难度

### ISSUE THREAD

**Issue by shengqin** [lamueno/classicDruid#9]
这个要战歌崇拜才能获取，难度应该是四星吧？

感谢你的文章，学到了很多。

**Comment by lamueno** [comment]
谢谢，已经修正了。

**Comment by shengqin** [comment]
P6阶段的NAXX会掉落单手锤 `梦境之末` 以及`谴责着` ， 和披风`支配披风`。要不要考虑添加进去？
